site_name: IRA Rebate API JSON Schema Static Site
site_url: https://pnnl.github.io/IRA-Rebates-API
repo_url: https://github.com/pnnl/IRA-Rebates-API
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: light)'
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  layout:
    width: full
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.33.1/plotly.min.js
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
- stylesheets/extra.css
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - codehilite
  - abbr
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
nav:
- Electric Install Redemptions Payload: electric_install_redemptions_payload/electric_install_redemptions_payload.md
- Homes Files Payload: homes_files_payload/homes_files_payload.md
- Electric Install Redemption Deletions Payload: electric_install_redemption_deletions_payload/electric_install_redemption_deletions_payload.md
- Electric Product Redemptions Payload: electric_product_redemptions_payload/electric_product_redemptions_payload.md
- Electric Product Redemption Deletions Payload: electric_product_redemption_deletions_payload/electric_product_redemption_deletions_payload.md
- Electric Reservations Expiration Date Updates Payload: electric_reservations_expiration_date_updates_payload/electric_reservations_expiration_date_updates_payload.md
- Homes Reservation Deletions Payload: homes_reservation_deletions_payload/homes_reservation_deletions_payload.md
- Address Service Payload: address_service_payload/address_service_payload.md
- Electric Vendor Coupon Redemption Deletion Payload: electric_vendor_coupon_redemption_deletion_payload/electric_vendor_coupon_redemption_deletion_payload.md
- Homes Eligible Rebates Payload: homes_eligible_rebates_payload/homes_eligible_rebates_payload.md
- Homes Reservations Expiration Date Updates Payload: homes_reservations_expiration_date_updates_payload/homes_reservations_expiration_date_updates_payload.md
- Electric Bulk Reporting Payload: electric_bulk_reporting_payload/electric_bulk_reporting_payload.md
- Electric Eligible Rebates Payload: electric_eligible_rebates_payload/electric_eligible_rebates_payload.md
- Homes Reservations Payload: homes_reservations_payload/homes_reservations_payload.md
- Electric Vendor Coupon Redemptions Payload: electric_vendor_coupon_redemptions_payload/electric_vendor_coupon_redemptions_payload.md
- Homes State Addenda Payload: homes_state_addenda_payload/homes_state_addenda_payload.md
- Homes Redemptions Payload: homes_redemptions_payload/homes_redemptions_payload.md
- Applicant Ids Payload: applicant_ids_payload/applicant_ids_payload.md
- Homes Bulk Reporting Payload: homes_bulk_reporting_payload/homes_bulk_reporting_payload.md
- Electric Limited Assessments Payload: electric_limited_assessments_payload/electric_limited_assessments_payload.md
- Electric State Addenda Payload: electric_state_addenda_payload/electric_state_addenda_payload.md
- Homes Redemption Deletions Payload: homes_redemption_deletions_payload/homes_redemption_deletions_payload.md
- Electric Reservations Payload: electric_reservations_payload/electric_reservations_payload.md
- Electric Reservation Deletions Payload: electric_reservation_deletions_payload/electric_reservation_deletions_payload.md
- Electric Files Payload: electric_files_payload/electric_files_payload.md
